/*
Question #1: 
If we exclude the discounts that have been given, the expected profit margin for each product is calculated by: (retail price - cost) / retail price. 

Create a column that flags products with a name that includes “Vintage” as products from Nike Vintage and Nike Official otherwise. 

Calculate the expected profit margins for each product name and include the group that splits products between Nike Official and Nike Vintage in the result.
*/

-- Question #1 Solution:

SELECT 
  pr.product_name,
  
CASE WHEN pr.product_name LIKE '%Vintage%' THEN 'Nike Vintage'
	 ELSE 'Nike Official' 
     END AS business_unit, -- I used CASE WHEN to create a custom column to identify Nike Official and Nike Vintage products
     (pr.retail_price - pr.cost) / pr.retail_price AS profit_margin -- here I calculated a metric using minus and division
  
FROM products pr
  
LEFT JOIN order_items_vintage oiv ON oiv.product_id = pr.product_id -- I used JOINS to be able to calculate the metric across both business units and combine columns

LEFT JOIN order_items oi ON oi.product_id = oiv.product_id

GROUP BY pr.product_name, pr.retail_price, pr.cost

ORDER BY profit_margin DESC;

-- commenting on my observations about the output of my solution to question 1:
/* Being able to see the expected profit margins for each product and business unit in the result give us some more insight on the performance of each item.
Ordering the data by profit margin allow us to see which products are expected to generate a higher or lower profit margin so we can focus on puhsing the latter. 
*/

/*
Question #2: 
What is the profit margin for each distribution center? Are there any centers that stand out?
*/

-- Question #2 Solution:

SELECT dc.name,
SUM(pr.retail_price - pr.cost) / SUM(pr.retail_price) AS profit_margin -- I aggregated the data and calculated the expected profit margin for multiple products

FROM distribution_centers dc

JOIN products pr ON dc.distribution_center_id = pr.distribution_center_id -- I used JOINS to combine data from products and distribution centers together

GROUP BY dc.name

ORDER BY profit_margin DESC;

-- commenting on my observations about the output of my solution to question 2:
/* Being able to see the expected profit margins for each distribution center give us a clear picture of which distribution centers are performing better. 
By ordering the data by profit margin wee can see that Memphis, Chicago and Mobile are standing out.
*/

/*
Question #3: 
The real profit margin per order item is calculated by: (sales price - cost) / sales price. By summing up all the order items, we will find the real profit margin generated by the products.

Calculate the profit margin for the Nike Official products: Nike Pro Tights, Nike Dri-FIT Shorts, and Nike Legend Tee
*/

-- Question #3 Solution:

SELECT pr.product_name,
SUM(oi.sale_price - pr.cost) / SUM(oi.sale_price) AS profit_margin -- here I aggregated the data while calculating the real profit margin
       
FROM products pr

JOIN order_items oi ON oi.product_id = pr.product_id -- I used JOINS to combine the product data with the order items together

WHERE pr.product_name IN ('Nike Pro Tights', 'Nike Dri-FIT Shorts', 'Nike Legend Tee')

GROUP BY pr.product_name

ORDER BY profit_margin DESC;;

-- commenting on my observations about the output of my solution to question 3:
/* When we find out the real profit margin for the requested order items and order them by profit margin we can clearly see the Nike Legend Tee is standing out.
*/


/*
Question #4: 
Calculate the real profit margin by product and split the data using the created date before 2021-05-01 and post 2021-05-01 for Nike Official order items.
*/

-- Question #4 Solution:

SELECT pr.product_name,

CASE WHEN oi.created_at < '2021-05-01' THEN 'Pre-May'
     ELSE 'Post-May'
     END AS may21_split, -- I used CASE WHEN to create a column that splits the data into two groups
     SUM(oi.sale_price - pr.cost) / SUM(oi.sale_price) AS profit_margin -- here I aggregated the data while calculating the real profit margin
       
FROM products pr

INNER JOIN order_items oi ON oi.product_id = pr.product_id

GROUP BY pr.product_name, may21_split

ORDER BY pr.product_name, may21_split;

-- commenting on my observations about the output of my solution to question 4:
/* When we find out the real profit margin for the requested periods of time we can compare them and find out that the has been a tendency of improvement after May in the Nike Official items.
*/

/*
Question #5: 
Calculate the profit margin by product for both Nike Official and Nike Vintage products in a single view 
*/

-- Question #5 Solution:

SELECT pr.product_name,

SUM(oi.sale_price - pr.cost) / SUM(oi.sale_price) AS profit_margin -- here I aggregate data by a specific product
       
FROM products pr

INNER JOIN order_items oi ON oi.product_id = pr.product_id

GROUP BY pr.product_name

UNION ALL -- I used UNION to combine rows from two data sources into a single result

SELECT pr.product_name,

SUM(oiv.sale_price - pr.cost) / SUM(oiv.sale_price) AS profit_margin
       
FROM products pr

INNER JOIN order_items_vintage oiv ON oiv.product_id = pr.product_id

GROUP BY pr.product_name

ORDER BY profit_margin DESC;;

-- commenting on my observations about the output of my solution to question 5:
/* When we find out the profit margin for all order items in each business unit and order them by profit margin we can see which products are standing out and that the top two are Nike Vintage products.
*/

/*
Question #6: 
What are the top 10 products by profit margin from Nike Official and Nike Vintage? 
Include the product name, profit margin, and what business unit (Nike Official or Nike Vintage) sells the product.
*/

-- Question #6 Solution:

SELECT 'Nike Official' AS business_unit,
		pr.product_name,

SUM(oi.sale_price - pr.cost) / SUM(oi.sale_price) AS profit_margin
       
FROM products pr

INNER JOIN order_items oi ON oi.product_id = pr.product_id

GROUP BY pr.product_name

UNION ALL -- I used UNION to combine rows from two data sources into a single result

SELECT 'Nike Vintage' AS business_unit,
	    pr.product_name,

SUM(oiv.sale_price - pr.cost) / SUM(oiv.sale_price) AS profit_margin
       
FROM products pr

INNER JOIN order_items_vintage oiv ON oiv.product_id = pr.product_id

GROUP BY pr.product_name

ORDER BY profit_margin DESC -- here I ordered the products by profit margin 

LIMIT 10; -- here I limited the rows to 10 to get the top 10 products by profit margin form both business units

-- commenting on my observations about the output of my solution to question 6:
/* When we find out the profit margin for all order items in each business unit and order them by profit margin we can see the top 10 products that are standing out.
*/
